// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnlacaqhdhavkafumhrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndubGFjYXFoZGhhdmthZnVtaHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDE5NjcsImV4cCI6MjA2NjY3Nzk2N30.oACK8JZOWrbiAxup6W-0-kDGYfsrCTBui5ecs7dwAk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);